### ISSUE TITLE
Add iCubGenova04 

### ISSUE THREAD

**Issue by traversaro** [robotology-playground/icub-model-generator#43]
It is a classical iCub 2.5 with backpack, so it should be simple.

**Comment by traversaro** [comment]
@gabrielenava can you take care of this? It should be just necessary adding some lines in https://github.com/robotology-playground/icub-model-generator/blob/master/simmechanics/CMakeLists.txt#L44 and probably adding the tests in https://github.com/robotology-playground/icub-model-generator/blob/e3b35c515acd31a1b31119a0dd3f4dcad8a0a82a/tests/CMakeLists.txt#L29 .

**Comment by francesco-romano** [comment]
@traversaro without backpack, isn't it?

**Comment by traversaro** [comment]
![image 2017-05-03 12 24 49](https://cloud.githubusercontent.com/assets/1857049/25656893/80f103ee-2ffb-11e7-85ac-a0b7ff3c24a6.jpg) ?

**Comment by francesco-romano** [comment]
You know that I was sure that iCubGenova04 was without backpack?!?!?!

**Comment by traversaro** [comment]
Done in https://github.com/robotology-playground/icub-model-generator/issues/45 .
