### ISSUE TITLE
Change feet collision meshes to a simpler primitive shape

### ISSUE THREAD

**Issue by nunoguedelha** [robotology-playground/icub-model-generator#77]
The collision meshes in the foot should be substituted with a simpler primitive shapes (box or four spheres). This would improve the simulation performance and reduce the computations for estimating the contact forces.

**Comment by fiorisi** [comment]
The iCub foot has a quite complex shape. The SDF format provides 3 possible viable solutions to approximate the collision geometry.

### [Sphere][1]
In theory, we can have 4 or more little spheres on each corner of the foot. The major drawback, in this case, is that collisions that don't involve the spheres are not detected (i.e. the foot volume can intersect with a step, if the step edge is in contact only with the center of the sole).
![foot_approx5](https://user-images.githubusercontent.com/8970230/32697966-22c4e608-c79c-11e7-8eb3-3b6547d0f21e.png)

 
### [Box][2]
In this case, we can either draw a box smaller than the foot or a bit bigger.
![foot_approx3](https://user-images.githubusercontent.com/8970230/32697986-5c547028-c79c-11e7-95d1-f5658e84cf3a.png)
![foot_approx](https://user-images.githubusercontent.com/8970230/32697987-615b2e0e-c79c-11e7-872c-81ae7bf07a7c.png)

### [Polyline][3]
Starting from SDF version 1.5, it is possible to use also polylines. In this case we can better approximate the foot shape. If we go for this geometry, we need to update the [supported geometries][4] in the [simmechanics-to-urdf][5] tool.
![foot_approx2](https://user-images.githubusercontent.com/8970230/32698008-c27d6bc0-c79c-11e7-9026-34bd43fe3de7.png)
![foot_approx4](https://user-images.githubusercontent.com/8970230/32698009-c55723f4-c79c-11e7-81ee-71cb551811e9.png)

[1]:http://sdformat.org/spec?ver=1.6&elem=geometry#geometry_sphere
[2]:http://sdformat.org/spec?ver=1.6&elem=geometry#geometry_box
[3]:http://sdformat.org/spec?ver=1.6&elem=geometry#geometry_polyline
[4]:https://github.com/robotology/simmechanics-to-urdf/blob/master/simmechanics_to_urdf/firstgen.py#L37
[5]:https://github.com/robotology/simmechanics-to-urdf

**Comment by nunoguedelha** [comment]
We decided to go for the use of polylines for defining the collision geometry. As a reminder: the library package GTS has to be installed. It has been checked in macos that the library can be installed with Gazebo by upgrading to latest version 8.1.1.7 through Homebrew.
The **simmechanics-to-urdf** dependency is implemented by ...

**Comment by nunoguedelha** [comment]
### Background
#### Collision geometry and Polyline definition in the SDF model
A link can contain multiple collision elements (refer to `collision` definition in [this Gazebo tutorial](http://gazebosim.org/tutorials?tut=build_model)). For instance:
```
<link name='l_foot'>
  ...
  <collision name='l_foot_collision'>
      ...
  </collision>
  <collision name='l_foot_collision_2'>
      ...
  </collision>
  ...
</link>
```
In each collision element, only the first defined geometry element will be considered, the remaining ones ignored. 

#### Collision geometry and Polyline definition in the URDF model
As per the URDF specification [here](http://wiki.ros.org/urdf/XML/link), Polyline shapes are not supported in URDF format.
[Multiple collision bodies](http://wiki.ros.org/urdf/XML/link) are not supported in URDF either. Custom collision elements, for instance meant for collision checking by a controller, can be added wrapped in a custom tag—<collision_XXXXX>—which will be ignored by the ROS URDF parser.

#### Supported URDF to SDF conversions
Polyline shapes are ignored by the Gazebo parser if embedded in a URDF file. For this reason, the Polyline parameters must be embedded in a `<gazebo>` tag.

**Comment by nunoguedelha** [comment]
### Requirements

#### Desired resulting collision geometry in SDF format
- The overall desired foot collision geometry would be defined in the URDF or explicitely in a SDF block wrapped in a tag `<gazebo>`
- the geometry is composed by the union of:
    - the upper part of the sole mesh
    - the extruded polyline shaping the contact with the ground

We give [here](https://github.com/robotology-playground/icub-model-generator/wiki/Example-models-(URDF,-SDF)-of-a-standalone-foot-link-with-simplified-collision-geometry#collision-shape-based-on-multiple-collision-elements) an example of a model composed by a standalone foot link with simplified collision geometry. The extruded polyline geometry element between the foot mesh and the ground has 4 points and an exagerated height for making it more visible.
<attached image>

#### YAML config parameters
The Polyline shapes are required only for iCub Gazebo models so they could be inserted through Cmake while generating the YAML config file, as for the chest assigned mass `@CHEST_ASSIGNED_MASS@` or the links assigned inertias `@GAZEBO_ASSIGNED_INERTIAS@` variables. Considering the current partial support of polylines, it would be preferable to use the polylines only on iCub Gazebo models. The input parameters to define are as follows:
```
point: [<x1>,<y1>]
point: [<x2>,<y2>]
...
height: <h>
```
#### Derived requirements
Considering the constraints on defining Polylines in URDF and on the `<gazebo>` tag behavior, the retained solution would be to define two new links "l_sole" and "r_sole", wrapped in a `<gazebo>` tag, including only a `collision` and `inertial` blocks (no visual block) and rigidly fixed respectively to the left and right foot links.

**Comment by fiorisi** [comment]
Thanks @nunoguedelha for the analysis. Do you think that we need the collision in the URDF? Otherwise, for the time being, I would keep is simple: use the polyline as the collision geometry of the sole for all the models (also the one that we don't use in Gazebo).

**Comment by nunoguedelha** [comment]
### Solution 2 Requirements

#### Foot link change in the URDF 
Replace the collision mesh by the box defined through the YAML config parameters.

#### YAML config parameters
As for the previous solution, the collision box is required only for iCub Gazebo models so the parameters could be inserted through Cmake when generating the YAML file from the YAML template. The input parameters would be generated in the YAML file as:
```
collisionShapes:
  - linkName: l_foot
    type: box
    xyz: [<x>,<y>,<z>]
    originXYZ: [<x>,<y>,<z>]
    originRPY: [<r>,<p>,<y>]
  - linkName: r_foot
    ...
```

**Comment by nunoguedelha** [comment]
> Thanks @nunoguedelha for the analysis. Do you think that we need the collision in the URDF? Otherwise, for the time being, I would keep is simple: use the polyline as the collision geometry of the sole for all the models (also the one that we don't use in Gazebo).

Well, if we go for the Polyline choice (solution 1), it requires defining two new links "l_sole" and "r_sole" that we fixe to the feet. restraining it to Gazebo models through Cmake is no big deal and avoids adding complexity (additional links) to the other models.
Consider that sooner or later, Polylines should be supported also in URDF, or at least by the Gazebo URDF parser (unless they don't use any layer over the `urdfdom` parser), and only then we can replace the mesh or add to it the polylines within the foot link definition.

The biggest simplification would be to use just a box for now, on all models or just the Gazebo model.

**Comment by nunoguedelha** [comment]
If we go for solution 1, we can roceed as follows:
- replace the feet mesh by a box on all models
- add a second geometry in the foot collision element labeled `<collision_controller_check>` that would be ignored by Gazebo, and could be parsed any of our controllers if required.

**Comment by traversaro** [comment]
> Consider that sooner or later, Polylines should be supported also in URDF, or at least by the Gazebo URDF parser (unless they don't use any layer over the urdfdom parser) 

I am afraid Gazebo will never support Polylines in URDF files.

**Comment by nunoguedelha** [comment]
After last discussion with @fiorisi , we decided to go for solution 2, until a better support of polylines is available:
- replace the feet mesh by a box on all models
The `simmechanics-to-urdf` parser already supports replacing meshes with simple geometric shapes, as it was tested on R1.

**Comment by fiorisi** [comment]
Possible sole approximation (the foot frame is relative to iCub 2.5).
![l_sole_approximation](https://user-images.githubusercontent.com/8970230/34622095-0d10ce32-f24c-11e7-84d2-ae066c1cc187.png)
![l_sole_approximation2](https://user-images.githubusercontent.com/8970230/34622097-1009fcf8-f24c-11e7-8178-c2d881cbee66.png)

**Comment by fiorisi** [comment]
Solved with https://github.com/robotology-playground/icub-model-generator/commit/bc1ed7765d51be14a323b02cbe1936644e029d22.

**Comment by traversaro** [comment]
In the future, to do this automatically (and more importantly, systematically) it could make sense to investigate the use of approximate convex decomposition techniques such as https://github.com/kmammou/v-hacd/ .

**Comment by traversaro** [comment]
cc @aerydna @claudiofantacci @xEnVrE
