### ISSUE TITLE
wrong URDF fine calibration configuration

### ISSUE THREAD

**Issue by iron76** [robotology-playground/icub-model-generator#8]
When putting the urdf-iCub in the ``fine calibration'' configuration (http://wiki.icub.org/wiki/ArmFineCalibration) there is an apparent error in the (left and right) shoulder joint position. This is probably due to a wrong alignment of the torso with the arms.

**Comment by traversaro** [comment]
A robust way to proceed is to add to the `icub-tests` suite a consistency check on the transform provided used in iCub. The consistency check can test both `iKin` - `iDyn` consistency, and also `iKin` - `iDynTree` consistency. In this way, we already have a future place for testing consistency regardless of the how this model are produced (for example if in the future we will produce iKin chains from URDF the test will check that the converter is properly working.

**Comment by traversaro** [comment]
Unable to reproduce. On my machine, `iKin`/`iDyn`/`URDF` results are consistent,
Furthermore, on Gazebo the arm fine calibration joint positions match the expected result as reported in http://wiki.icub.org/wiki/ArmFineCalibration . (See attached image). 
![screenshot - 24032015 - 22 47 49](https://cloud.githubusercontent.com/assets/1857049/6813747/5e51cb26-d278-11e4-8e8c-3d812d0e3b35.png)

**Comment by iron76** [comment]
Covers are however rotated (see figure below) but kinematics seems to be consistent. Is this slight misalignment affecting any other component?

![screen shot 2015-03-25 at 13 02 04](https://cloud.githubusercontent.com/assets/4137836/6824112/3764ebfc-d2ef-11e4-97f8-2c1af4000e2b.png)

**Comment by traversaro** [comment]
Cover meshes are just used in simulation for display and collision checking. Given that for now we don't have any use case regarding contacts on the `*_upper_arm`, it is a just a visualization issue.
