### ISSUE TITLE
Error while loading iCubGazeboV2_5 in Gazebo with the new COUPLING parameters

### ISSUE THREAD

**Issue by gabrielenava** [robotology-playground/icub-model-generator#89]
I downloaded [icub-models]() and I tried to load the model in Gazebo. The robot collapsed on the floor. Here is the error that I see in the terminal:

```
[DEBUG]Requested couplings: COUPLING (matrixJ2M (1.0 0.0 0.0 0.0 -1.625 1.625 0.0 0.0 0.0 0.0 1.625 0.0 0.0 0.0 0.0 1.0) (1.0 0.0 0.0 0.0 1.0 0.0 0.0 -1.0 1.0)) 
[DEBUG]Size:  2 
[ERROR]Unknown coupling type 
yarpdev: ***ERROR*** driver <gazebo_controlboard> was found but could not open
[ERROR]GazeboYarpControlBoard : controlBoard < right_arm_no_hand > did not open. 
```

That seems related to the wrong usage of `couplings` keyword in the controlboard plugins.

**Comment by traversaro** [comment]
Keeping this open to find a proper solution per @nunoguedelha .

**Comment by fiorisi** [comment]
As discussed with @nunoguedelha, we close the issue.
@nunoguedelha will open a new PR to reintegrate the "coupling matrices".
